---
# add RPM repo

- name: add Apache Bigtop Repo
  ansible.builtin.yum_repository:
    name: bigtop
    description: bigtop repo
    baseurl: http://repos.bigtop.apache.org/releases/{{ bigtop_version }}/rockylinux/8/$basearch
    gpgkey: https://dist.apache.org/repos/dist/release/bigtop/KEYS
    gpgcheck: yes
    enabled: yes
